---
- name: Run all playbooks
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Execute postgres playbook
      command: ansible-playbook -i inventory ./postgresql_container/postgresql.yml

    - name: Execute apache playbook
      command: ansible-playbook -i inventory ./git_container/git.yml

    - name: Execute git playbook
      command: ansible-playbook -i inventory ./apache_container/apache.yml

